#!/bin/bash

# -------------------------------------------------------------------------- #
# Copyright 2002-2026, OpenNebula Project, OpenNebula Systems                #
#                                                                            #
# Licensed under the Apache License, Version 2.0 (the "License"); you may    #
# not use this file except in compliance with the License. You may obtain    #
# a copy of the License at                                                   #
#                                                                            #
# http://www.apache.org/licenses/LICENSE-2.0                                 #
#                                                                            #
# Unless required by applicable law or agreed to in writing, software        #
# distributed under the License is distributed on an "AS IS" BASIS,          #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   #
# See the License for the specific language governing permissions and        #
# limitations under the License.                                             #
#--------------------------------------------------------------------------- #

###############################################################################
# This script is used to set an IP address as free. The IP will be released
# by OpenNebula VMs
#
# This scripts MUST exit 0 if the address is freed.
#
# STDIN Input:
#   - Base64 encoded XML with the AR description and the address request
#
# Input arguments:
#   $1 - Request ID
#
# XML format
#  <IPAM_DRIVER_ACTION_DATA>
#  <AR>
#    <TYPE>IP4</TYPE>
#    <IP> First IP in the network in '.' notation
#    <MAC> First MAC in the network in ':' notation
#    <SIZE>Number of IPs in the network
#    <NETWORK_ADDRESS> Base network address
#    <NETWORK_MASK> Network mask
#    <GATEWAY> Default gateway for the network
#    <DNS> DNS servers, a space separated list of servers
#    <GUEST_MTU> Sets the MTU for the NICs in this network
#    <SEARCH_DOMAIN> for DNS client
# <ADDRESS>
#   <IP>
#   <SIZE> Number of IPs to allocate
#   <MAC> MAC is optional
#
################################################################################

# ----------- Set up the environment to source common tools & conf ------------

if [ -z "${ONE_LOCATION}" ]; then
    LIB_LOCATION=/usr/lib/one
else
    LIB_LOCATION=$ONE_LOCATION/lib
fi

. "$LIB_LOCATION/sh/scripts_common.sh"

DRIVER_PATH=$(dirname "$0")
. "${DRIVER_PATH}/common.sh"

# --------------- Get IPAM attributes from OpenNebula core --------------------

ID="$1"
DRV_ACTION=$(cat)

XPATH="${DRIVER_PATH}/../../datastore/xpath.rb -b $DRV_ACTION"

unset i XPATH_ELEMENTS

while IFS= read -r -d '' element; do
    XPATH_ELEMENTS[i++]="$element"
done < <($XPATH     /IPAM_DRIVER_ACTION_DATA/AR/TYPE \
                    /IPAM_DRIVER_ACTION_DATA/AR/MAC \
                    /IPAM_DRIVER_ACTION_DATA/AR/IP \
                    /IPAM_DRIVER_ACTION_DATA/AR/SIZE \
                    /IPAM_DRIVER_ACTION_DATA/AR/NETWORK_MASK \
                    /IPAM_DRIVER_ACTION_DATA/ADDRESS/IP \
                    /IPAM_DRIVER_ACTION_DATA/ADDRESS/SIZE)
unset i

AR_TYPE="${XPATH_ELEMENTS[i++]}"
AR_MAC="${XPATH_ELEMENTS[i++]}"
AR_IP="${XPATH_ELEMENTS[i++]}"
AR_SIZE="${XPATH_ELEMENTS[i++]}"
AR_NETWORK_MASK="${XPATH_ELEMENTS[i++]}"
ADDR_IP="${XPATH_ELEMENTS[i++]}"
ADDR_SIZE="${XPATH_ELEMENTS[i++]}"

# NOTE: Custom attributes can be get from the AR, and set when defining the
# network in the register_address_range action

#-------------------------------------------------------------------------------
# IPAM should be contact here to free the ADDR_IP. Note that several continous
# addresses can be requested
#-------------------------------------------------------------------------------

#-------------------------------------------------------------------------------
# BlueCat integration
#-------------------------------------------------------------------------------

bluecat_load_config

bluecat_log_block "free_address" \
  "Request ID: $ID" \
  "AR_IP=$AR_IP" \
  "AR_SIZE=$AR_SIZE" \
  "ADDR_IP=$ADDR_IP" \
  "ADDR_SIZE=$ADDR_SIZE" \
  "BLUECAT_MOCK=$BLUECAT_MOCK"
bluecat_log_decoded_action

#-------------------------------------------------------------------------------
# Mock mode
#-------------------------------------------------------------------------------

if [ "$BLUECAT_MOCK" = "yes" ]; then
  bluecat_log "Mock mode enabled, skipping BlueCat release for $ADDR_IP"
  exit 0
fi

#-------------------------------------------------------------------------------
# Real BlueCat API integration
#
# TODO: Replace this provisional lookup/delete flow with the supported BlueCat
# BAM API release workflow, including idempotent handling for addresses already
# free and support for releasing contiguous address ranges.
#-------------------------------------------------------------------------------

bluecat_require_real_api_config

bluecat_release_ip() {
  local ip="$1"
  local response
  local rc
  local id

  response=$(curl -fsS -u "$BLUECAT_USER:$BLUECAT_PASS" \
    -H "Accept: application/hal+json" \
    --get \
    --data-urlencode "filter=address:'${ip}'" \
    "$BLUECAT_URL/api/v2/addresses" 2>&1)
  rc=$?

  {
    echo "--- BlueCat lookup address response ---"
    echo "$response"
    echo "--- curl rc: $rc ---"
    echo
  } >> "$BLUECAT_LOG"

  if [ "$rc" -ne 0 ]; then
    bluecat_log "ERROR: BlueCat address lookup failed for $ip"
    return 1
  fi

  id=$(echo "$response" | jq -r '
    if type == "array" then
      .[0].id // .[0].objectId // empty
    else
      .id // .objectId // .data[0].id // .data[0].objectId //
      .results[0].id // .results[0].objectId //
      ._embedded.addresses[0].id // ._embedded.addresses[0].objectId //
      empty
    end')

  if [ -z "$id" ] || [ "$id" = "null" ]; then
    bluecat_log "BlueCat address $ip not found, treating as already free"
    return 0
  fi

  response=$(curl -fsS -u "$BLUECAT_USER:$BLUECAT_PASS" \
    -H "Accept: application/hal+json" \
    -X DELETE \
    "$BLUECAT_URL/api/v2/addresses/${id}" 2>&1)
  rc=$?

  {
    echo "--- BlueCat delete address response ---"
    echo "$response"
    echo "--- curl rc: $rc ---"
    echo
  } >> "$BLUECAT_LOG"

  if [ "$rc" -ne 0 ]; then
    bluecat_log "ERROR: BlueCat address delete failed for $ip"
    return 1
  fi
}

if ! bluecat_release_ip "$ADDR_IP"; then
  echo "-1"
  exit 1
fi

exit 0
