#!/bin/bash

# -------------------------------------------------------------------------- #
# Copyright 2002-2026, OpenNebula Project, OpenNebula Systems                #
#                                                                            #
# Licensed under the Apache License, Version 2.0 (the "License"); you may    #
# not use this file except in compliance with the License. You may obtain    #
# a copy of the License at                                                   #
#                                                                            #
# http://www.apache.org/licenses/LICENSE-2.0                                 #
#                                                                            #
# Unless required by applicable law or agreed to in writing, software        #
# distributed under the License is distributed on an "AS IS" BASIS,          #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   #
# See the License for the specific language governing permissions and        #
# limitations under the License.                                             #
#--------------------------------------------------------------------------- #

###############################################################################
# This script is used to unregister an AddresRange from the IPAM.
#
# The IPAM driver must return 0 if no errors.
#
# STDIN Input:
#   - Base64 encoded XML with AR request
#
# Input arguments:
#   $1 - Request ID
#
# XML format
#  <IPAM_DRIVER_ACTION_DATA>
#  <AR>
#    <TYPE>IP4</TYPE>
#    <IP> First IP in the network in '.' notation
#    <MAC> First MAC in the network in ':' notation
#    <SIZE>Number of IPs in the network
#    <NETWORK_ADDRESS> Base network address
#    <NETWORK_MASK> Network mask
#    <GATEWAY> Default gateway for the network
#    <DNS> DNS servers, a space separated list of servers
#    <GUEST_MTU> Sets the MTU for the NICs in this network
#    <SEARCH_DOMAIN> for DNS client
#
################################################################################

# ----------- Set up the environment to source common tools & conf ------------

if [ -z "${ONE_LOCATION}" ]; then
    LIB_LOCATION=/usr/lib/one
else
    LIB_LOCATION=$ONE_LOCATION/lib
fi

. "$LIB_LOCATION/sh/scripts_common.sh"

# --------------- Get IPAM attributes from OpenNebula core --------------------

DRIVER_PATH=$(dirname "$0")
. "${DRIVER_PATH}/common.sh"

ID="$1"
DRV_ACTION=$(cat)

XPATH="${DRIVER_PATH}/../../datastore/xpath.rb -b $DRV_ACTION"

unset i XPATH_ELEMENTS

while IFS= read -r -d '' element; do
    XPATH_ELEMENTS[i++]="$element"
done < <($XPATH     /IPAM_DRIVER_ACTION_DATA/AR/TYPE \
                    /IPAM_DRIVER_ACTION_DATA/AR/IP \
                    /IPAM_DRIVER_ACTION_DATA/AR/SIZE \
                    /IPAM_DRIVER_ACTION_DATA/AR/NETWORK_MASK \
                    /IPAM_DRIVER_ACTION_DATA/AR/GATEWAY \
                    /IPAM_DRIVER_ACTION_DATA/AR/DNS \
                    /IPAM_DRIVER_ACTION_DATA/AR/BLUECAT_NETWORK_ID)

unset i

TYPE="${XPATH_ELEMENTS[i++]}"
IP="${XPATH_ELEMENTS[i++]}"
SIZE="${XPATH_ELEMENTS[i++]}"
NETWORK_MASK="${XPATH_ELEMENTS[i++]}"
GATEWAY="${XPATH_ELEMENTS[i++]}"
DNS="${XPATH_ELEMENTS[i++]}"
BLUECAT_NETWORK_ID_AR="${XPATH_ELEMENTS[i++]}"

#-------------------------------------------------------------------------------
# BlueCat integration
#-------------------------------------------------------------------------------

bluecat_load_config

BLUECAT_NETWORK_ID_FINAL="${BLUECAT_NETWORK_ID_AR:-$BLUECAT_NETWORK_ID}"

bluecat_log_block "unregister_address_range" \
  "Request ID: $ID" \
  "TYPE=$TYPE" \
  "IP=$IP" \
  "SIZE=$SIZE" \
  "NETWORK_MASK=$NETWORK_MASK" \
  "GATEWAY=$GATEWAY" \
  "DNS=$DNS" \
  "BLUECAT_NETWORK_ID=$BLUECAT_NETWORK_ID_FINAL" \
  "BLUECAT_MOCK=$BLUECAT_MOCK"
bluecat_log_decoded_action

#-------------------------------------------------------------------------------
# Mock mode
#-------------------------------------------------------------------------------

if [ "$BLUECAT_MOCK" = "yes" ]; then
  bluecat_log "Mock mode enabled, skipping BlueCat AR unregister for $IP/$SIZE"
  exit 0
fi

#-------------------------------------------------------------------------------
# Real BlueCat API integration
#
# TODO: Replace this provisional delete/keep behavior with the supported
# BlueCat BAM API workflow, including reference cleanup and policy checks for
# whether OpenNebula is allowed to delete the backing BlueCat network.
#-------------------------------------------------------------------------------

case "$BLUECAT_UNREGISTER_ACTION" in
  delete|DELETE)
    bluecat_require_curl_api_config

    if [ -z "$BLUECAT_NETWORK_ID_FINAL" ]; then
      bluecat_fail "Missing BLUECAT_NETWORK_ID, cannot delete BlueCat network"
    fi

    RESPONSE=$(curl -fsS -u "$BLUECAT_USER:$BLUECAT_PASS" \
      -H "Accept: application/hal+json" \
      -X DELETE \
      "$BLUECAT_URL/api/v2/networks/${BLUECAT_NETWORK_ID_FINAL}" 2>&1)
    RC=$?

    {
      echo "--- BlueCat delete network response ---"
      echo "$RESPONSE"
      echo "--- curl rc: $RC ---"
      echo
    } >> "$BLUECAT_LOG"

    if [ "$RC" -ne 0 ]; then
      bluecat_fail "BlueCat network delete failed for $BLUECAT_NETWORK_ID_FINAL"
    fi
    ;;
  *)
    bluecat_log "BLUECAT_UNREGISTER_ACTION=${BLUECAT_UNREGISTER_ACTION:-keep}, keeping BlueCat network $BLUECAT_NETWORK_ID_FINAL"
    ;;
esac

exit 0
